import type { reportFr } from "./report.fr"

// Namespace i18n « report » (EN) — doit refléter les clés de reportFr.
type Widen<T> = T extends string ? string : { [K in keyof T]: Widen<T[K]> }
export const reportEn: Widen<typeof reportFr> = {
  report: {
    periodLabel: "June 2026",
    actions: {
      backToPerformance: "Performance",
      customize: "Customize",
      sectionsTitle: "Report sections",
      copyLink: "Copy link",
      exportPdf: "Export to PDF",
      copiedTitle: "Preview link copied (preview)",
      copiedDescription:
        "In production: a frozen link with a revocable token, no account required.",
      readyTitle: "Preview link ready (preview)",
      printTitle: "Opening print dialog…",
      printDescription: 'Choose "Save as PDF" in the dialog.',
    },
    section: {
      kpis: "Key figures",
      highlights: "Top posts",
      mix: "Content mix",
      note: "A word from your community manager",
    },
    header: {
      monthlyReview: "Monthly review · {period}",
      igFollowers: "Instagram followers",
    },
    summary: {
      title: "At a glance",
      line1: "This month, {count, plural, one {# post} other {# posts}} reached {reach} accounts.",
      line2: "Your content generated {engagement} interactions (likes, comments and saves).",
      line3:
        "Posting cadence is on track and the content mix stays true to the editorial line we defined together.",
    },
    kpi: {
      reach: "Reach",
      engagement: "Engagements",
      rate: "Engagement rate",
      count: "Posts",
      vsPreviousMonth: "{delta} vs last month",
    },
    highlights: {
      title: "Your top posts",
      stats: "{reach} views · {engagement} interactions",
    },
    mix: {
      title: "Content mix",
      pillarTitle: "{name} · {share}",
    },
    note: {
      title: "Word of the month",
      ariaLabel: "Community manager's summary note",
      default:
        "A steady month, true to your editorial line. Next month we'll build on the formats that resonated most with your community, and keep this publishing pace.",
    },
    footer: {
      generatedBy: "Generated by Ocean",
      separator: "{name} · {period}",
    },
    printHint: 'Faithful print preview — use "Export to PDF" for the client deliverable.',
  },
}
